Repository FastCampus-MoReturn/final-project-Be, pull requests merged in 2023-04, with the labels that each got.

#19 Aws S3 도입 및 PDF 파싱 문제 해결
  build.gradle
  src/main/java/com/fastcampus/finalprojectbe/global/config/S3Config.java
  src/main/java/com/fastcampus/finalprojectbe/global/config/WebMvcConfig.java
  src/main/java/com/fastcampus/finalprojectbe/pdfparsing/service/impl/PdfParsingImpl.java
  src/main/java/com/fastcampus/finalprojectbe/publicapi/dto/TradingPriceIndexResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/publicapi/service/impl/PriceIndexApiServiceImpl.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Feature

#22 Fe 요청건 일부 완료.
  src/main/java/com/fastcampus/finalprojectbe/global/config/SwaggerConfig.java
  src/main/java/com/fastcampus/finalprojectbe/global/config/WebMvcConfig.java
  src/main/java/com/fastcampus/finalprojectbe/home/homeController.java
  src/main/java/com/fastcampus/finalprojectbe/pdfparsing/dto/PdfParsingResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/pdfparsing/service/impl/PdfParsingImpl.java
Labels: For: API, For: Backend, Status: Completed, Type: Feature

#25 코드 리팩토링 및 맵핑 변경
  src/main/java/com/fastcampus/finalprojectbe/global/config/SwaggerConfig.java
  src/main/java/com/fastcampus/finalprojectbe/global/response/CommonResponse.java
  src/main/java/com/fastcampus/finalprojectbe/global/xml/XmlReader.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/controller/ApiController.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/dto/TradingDetailReqDTO.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/dto/TradingDetailResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/dto/TradingPriceIndexResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/dto/tradingDetailResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/service/OpenApiService.java
  src/main/java/com/fastcampus/finalprojectbe/openapi/service/impl/OpenApiServiceImpl.java
  src/main/java/com/fastcampus/finalprojectbe/pdfparsing/dto/PdfParsingResDTO.java
Labels: For: Backend, Priority: Low, Status: Completed, Type: Documentation

#26 등기 용어 정리 사전 API #24
  src/main/java/com/fastcampus/finalprojectbe/terms/controller/TermsController.java
  src/main/java/com/fastcampus/finalprojectbe/terms/dto/TermsResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/terms/entity/Terms.java
  src/main/java/com/fastcampus/finalprojectbe/terms/repository/TermsRepository.java
  src/main/java/com/fastcampus/finalprojectbe/terms/service/TermsService.java
  src/main/java/com/fastcampus/finalprojectbe/terms/service/impl/TermsServiceImpl.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Feature

#30 등기 용어 정리 사전 API 수정사항
  src/main/java/com/fastcampus/finalprojectbe/global/config/PageableConfig.java
  src/main/java/com/fastcampus/finalprojectbe/global/exception/DataNotFoundException.java
  src/main/java/com/fastcampus/finalprojectbe/global/exception/ExceptionAdvice.java
  src/main/java/com/fastcampus/finalprojectbe/global/exception/KeywordValidationException.java
  src/main/java/com/fastcampus/finalprojectbe/terms/controller/TermsController.java
  src/main/java/com/fastcampus/finalprojectbe/terms/dto/TermsResDTO.java
  src/main/java/com/fastcampus/finalprojectbe/terms/entity/Terms.java
  src/main/java/com/fastcampus/finalprojectbe/terms/repository/TermsRepository.java
  src/main/java/com/fastcampus/finalprojectbe/terms/service/TermsService.java
  src/main/java/com/fastcampus/finalprojectbe/terms/service/impl/TermsServiceImpl.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Feature

#31 등기 용어 정리 사전 API 수정(오탈자)
  src/main/java/com/fastcampus/finalprojectbe/global/config/PageableConfig.java
  src/main/java/com/fastcampus/finalprojectbe/terms/controller/TermsController.java
  src/main/java/com/fastcampus/finalprojectbe/terms/repository/TermsRepository.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Bug

#33 등기 용어 사전 추가 요청사항
  src/main/java/com/fastcampus/finalprojectbe/global/config/PageableConfig.java
  src/main/java/com/fastcampus/finalprojectbe/terms/controller/TermsController.java
  src/main/java/com/fastcampus/finalprojectbe/terms/repository/TermsRepository.java
  src/main/java/com/fastcampus/finalprojectbe/terms/service/impl/TermsServiceImpl.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#34 등기 용어 사전 추가 요청 사항
  src/main/java/com/fastcampus/finalprojectbe/terms/service/impl/TermsServiceImpl.java
Labels: For: API, Priority: High, Status: Completed, Type: Bug

#35 등기 용어 사전 추가 요청 사항
  src/main/java/com/fastcampus/finalprojectbe/global/config/PageableConfig.java
Labels: For: API, Priority: High, Status: Completed, Type: Bug
